version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "01:00"
    open-pull-requests-limit: 10
    reviewers:
      - NotAShelf
    assignees:
      - NotAShelf
