name: Build

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      CACHIX_AUTH_TOKEN:
        required: false

jobs:
  build:
    strategy:
      matrix:
        package:
          - alejandra-custom
          - ani-cli
          - cloneit
          - foot-transparent
          - headscale-ui
          - mastodon-bird-ui
          - zsh-stripped

    uses: ./.github/workflows/nix.yml
    with:
      command: nix build -L .#${{ matrix.package }} -v
    secrets: inherit
