name: Build

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      CACHIX_AUTH_TOKEN:
        required: false

jobs:
  build:
    strategy:
      matrix:
        package:
          - foot-transparent
          - cloneit
          - mov-cli
          - rat
          - ani-cli
          - rofi-calc-wayland
          - rofi-emoji-wayland
          - headscale-ui

    uses: ./.github/workflows/nix.yml
    with:
      command: nix build -L .#${{ matrix.package }} -v
    secrets: inherit
